module.exports = {
    noscript_warning: 'Please turn on JavaScript.',

    signin_via_twitter: 'Sign in via Twitter',
    signin_via_vk: 'Sign in via VKontakte',
    signin_via_facebook: 'Sign in via Facebook',
    signin_via_other_vk: 'or via VKontakte',
    signin_via_other_twitter: 'or via Twitter',
    signin_via_other_facebook: 'or via Facebook',

    about: 'About',
    settings: 'Settings',
    search: 'Search',
    logout: 'Log out',
    edit: 'Edit',
    add: 'Add',
    delete: 'Delete',
    write: 'Write',
    hide: 'Hide',
    last_update: 'Last update',

    status_changed_my_mind: 'Change my mind',
    status_changed_my_mind_back: 'Change my mind back',
    status_presented: 'Presented',
    status_bought: 'Bought',
    status_private: 'Hidden wish',
    private_on: 'Make hidden',
    private_off: 'Make public',
    status_reservedByMe: 'Reserved by Me',
    status_remove_reserve: 'Remove reserve',
    status_reserved: 'Reserved',
    remove_status: 'Remove status',
    copy_wish: 'I want it too',
    post_on_vk: 'Post on VKontakte…',
    tweet: 'Write tweet…',
    write_post: 'Write on Facebook…'
    wish_added: 'Wish added to <a href="/{{username}}">your list</a>.',

    index_page_title: 'Your wishlist without bullshit',
    hide_wish_para: 'It’s a hidden wish, which is visible only to you.',

    index_page_bubble_head: 'Create your<br>wishlist',
    index_page_hearts_head: 'Group gifts<br>by themes',
    index_page_bird_head: 'Share link<br>with friends',
    index_page_gift_head: 'Receive only<br>the right gifts',
    index_page_facts_about_us: 'Some facts about us',
    index_page_follow_us: 'Follow us <a href="https://vk.com/wantr">in VKontakte</a>, <a href="https://twitter.com/wantr_ru">Twitter</a> and <a href="https://facebook.com/wantr.ru">Facebook</a>.',

    welcome_text: 'Write some welcome words.',
    wishes: 'Wishes',
    wishes_empty_for_stranger: 'The list is empty.',
    wishes_empty_for_owner: 'Your list is empty. Add something, don’t be shy.',
    antiwishes: 'Antiwishes',
    antiwishes_empty: 'The List is empty. Please add antiwishes. It’s a simple way to say “please, don’t gift me anything like this”.',

    birthday: 'Born',
    today: 'Today',
    hbd: 'Happy birthday!',
    turn: 'turn',
    add_bd: 'Add birthday',
    age_one: 'year old',
    age_two: 'years old',
    age_many: 'years old',

    find_friends: 'Find friends',
    add_friend: 'Add friend',
    delete_friend: 'Remove friend',
    no_friends: 'No friends',
    plural_friends_one: 'friend',
    plural_friends_two: 'friends',
    plural_friends_many: 'friends',

    month_later: 'Month later',
    three_weeks_later: 'Three weeks later',
    day_after_tomorrow: 'Day after tomorrow',
    tomorrow: 'Tomorrow',
    today_upper: 'Today',
    yesterday: 'Yesterday',
    just: 'just',
    after: 'After',
    day_one: 'day',
    day_two: 'days',
    day_many: 'days',
    hour_one: 'hour',
    hour_two: 'hours',
    hour_many: 'hours',
    minute_one: 'minute',
    minute_two: 'minutes',
    minute_many: 'minutes',
    ago: 'ago',

    months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
    ],

    no_search_results: 'No results', // TODO
    type_nickname_or_username: 'Type nickname or username',

    login_page_title: 'Who are you, stranger?',
    not_found_page_title: 'Page not found',
    not_found_page_para: 'Maybe you are looking for user «{{login}}»… but we don’t have them.',
    page_500_title: 'Something went wrong :(',
    internal_service_error: 'Internal service error',

    explore_page_title: '10 random selected users',
    refresh: 'Refresh',
    explore_page_para: 'Haven’t found anyone you know? Perhabs they’re not here yet… Invite them!',

    find_friends_page_title: 'Find friends',
    // Контекст: найти друзей на фейсбуке
    find_friends_page_facebook: 'on Facebook',
    find_friends_page_vkontakte: 'on VKontakte',
    find_friends_page_twitter: 'on Twitter',

    following_page_title: 'Friends',
    following_page_no_friends: 'No friends.',
    following_page_find_friends: 'Found <a href="/{{username}}/find-friends/">my friends</a> from {{social}}.',
    following_page_facebook: 'Facebook',
    following_page_vkontakte: 'VKontakte',
    following_page_twitter: 'Twitter',

    settings_page_title: 'Settings',
    settings_form_name: 'Name',
    settings_form_username: 'Nickname',
    settings_form_username_para: 'Used in your list address:',
    settings_form_username_is_free: 'is available',
    settings_form_username_is_not_free: 'is already taken',
    settings_form_username_mask: 'Only Latin lowercase letters, numbers and _ - .',
    settings_form_bd: 'Birthday',
    settings_form_hide_age: 'Hide age',
    settings_form_sex: 'Sex',
    settings_form_male: 'Male',
    settings_form_female: 'Female',
    settings_form_site: 'Site',
    settings_form_email_para: 'Fill you email if you want to be notified about you friend’s holidays and changes in reserved wishes.',
    settings_form_i_agree_to_delete_me: 'I want to delete my profile and all data. I understand than it couldn’t be reverted.',
    settings_form_delete_me: 'Delete my profile',
    settings_form_save_button_title: 'Save',
    settings_form_lang: 'Interface language',
    language_name: 'English',
    settings_form_facebook: 'on Facebook',
    settings_form_vkontakte: 'on VKontakte',
    settings_form_twitter: 'on Twitter',
    settings_form_avatar_from: 'Avatar loaded <a href="{{link}}" target="_blank">from your profile {{social}}</a>.',

    to_profile: 'To profile',
    welcome_text: 'Welcome text',
    welcome_text_placeholder: 'Welcome text', //'Можете написать вступление или пояснения, которые не выразить пунктами списка желаний',

    edit_page_antiwishes_descr: 'List what you do not want to see as a gift.', // 'Перечислите, чего вы не хотите видеть в качестве подарка.',
    edit_page_save_button_title: 'Save changes',
    edit_page_wish_descr: 'Description',
    edit_page_antiwish_descr: 'Description',
    edit_page_link_descr: 'Link',
    edit_page_price_descr: 'Price',

    find_friends_page_empty_list: 'Вы счастливчик! вы — первый, среди ваших друзей {{social}}, кто зарегистрировался нашем сервисе.',
    find_friends_page_empty_list_2: 'Расскажите друзьям и знакомым о Wantr-е!',

    category: 'Category',
    category_name: 'Category name:',
    create_category: 'Create new…',

    // titles
    html_title_api: 'API Docs',
    html_title_media: 'Guides and media files',
    'html_title_press-open': 'Press-release',
    html_title_friends: 'Friends',
    html_title_edit: 'Edit',
    html_title_settings: 'Settings',
    html_title_404: '404',
    html_title_500: '500',
    html_title_login: 'Who are you, stranger?',
    html_title_search: 'Search',
    'html_title_find-friends': 'Search friends',
    html_title_user: '{{placeholder}} — wishlist',
    html_title_ny2014: 'Happy New Year!',
    html_title_explore: 'Explore',
    html_title_default: 'Wantr.ru — create wishlist',

    smm_i_want: 'I want',
    smm_wishes: 'wishes',
    smm_antiwishes: 'antiwishes',
    smm_antiwishes_para: 'Please, dont gift me it',
    smm_title: 'Create wishlist; Group wishes by themes; Share link with friends; Receive only right gifts.', // 'Создайте список желаний; Сгруппируйте желания по темам; Поделитесь ссылкой с друзьями; Получайте только желанные подарки!',
    smm_slogan: '— Tell me what you want and I say create wishlist'
};
