module.exports = {
    noscript_warning: 'Для корректной работы сайта включите, пожалуйста, JavaScript.',

    signin_via_twitter: 'Войти через Твиттер',
    signin_via_vk: 'Войти через Вконтакте',
    signin_via_facebook: 'Войти через Фейсбук',
    signin_via_other_vk: 'или через Вконтакте',
    signin_via_other_twitter: 'или через Твиттер',
    signin_via_other_facebook: 'или через Фейсбук',

    about: 'О проекте',
    settings: 'Настройки',
    search: 'Поиск',
    logout: 'Выйти',
    edit: 'Править',
    add: 'Добавить',
    write: 'Написать',
    last_update: 'Последнее обновление',

    index_page_title: 'Список ваших желаний',

    index_page_bubble_head: 'Создайте<br>список<br>желаний',
    index_page_hearts_head: 'Сгруппируйте<br>желания<br>по&nbsp;темам',
    index_page_bird_head: 'Поделитесь<br>ссылкой<br>с&nbsp;друзьями',
    index_page_gift_head: 'Получайте<br>только<br>желанное',
    index_page_facts_about_us: 'Несколько фактов о нас',

    welcome_text: 'Напишите вступительный текст. Здесь может быть обращение к&nbsp;друзьям, которое не&nbsp;укладывается в&nbsp;пункты желаний.',
    wishes: 'Wishes',
    wishes_empty_for_stranger: 'Список желаний пуст.',
    wishes_empty_for_owner: 'Список пуст. Добавьте несколько желаний, мечтать полезно ;)',
    antiwishes: 'Antiwishes',
    antiwishes_empty: 'Список пуст. Добавьте антижелания. Это простой способ сказать «Пожалуйста, не дарите мне это».',

    birthday: 'День рождения',
    today: 'сегодня',
    hbd: 'Поздравляем с днем рождения!',
    turn_age: 'исполнится',
    add_bd: 'Укажите день рождения',

    find_friends: 'Найдите друзей',
    add_friend: 'Добавить в друзья',
    delete_friend: 'Удалить из друзей',
    no_friends: 'Нет друзей',
    plural_friends_one: 'друг',
    plural_friends_two: 'друга',
    plural_friends_many: 'друзей',

    month_later: 'Через месяц',
    three_weeks_later: 'Осталось 3 недели',
    day_after_tomorrow: 'Уже послезавтра',
    tomorrow: 'Завтра',
    today_upper: 'Сегодня',
    yesterday: 'День рождения был вчера',
    just: 'только что',
    after: 'Через',
    day_one: 'день',
    day_two: 'дня',
    day_many: 'дней',
    hour_one: 'час',
    hour_two: 'часа',
    hour_many: 'часов',
    minute_one: 'минуту',
    minute_two: 'минуты',
    minute_many: 'минут',
    ago: 'назад',

    months: [
        'января',
        'февраля',
        'марта',
        'апреля',
        'мая',
        'июня',
        'июля',
        'августа',
        'сентября',
        'октября',
        'ноября',
        'декабря'
    ],

    no_search_results: 'По вашему запросу ничего не найдено.',
    type_nickname_or_username: 'Введите ник или имя пользователя',

    login_page_title: 'Стой, кто идет?',
    not_found_page_title: 'Страница не найдена',
    page_500_title: 'Лежим и не жужжим',
    internal_service_error: 'Внутренняя ошибка сервиса',

    explore_page_title: '10 случайно выбранных пользователей',
    refresh: 'Обновить',
    explore_page_para: 'Не нашли знакомых лиц? Возможно, они еще не знают о нашем сервисе... пригласите их!',

    find_friends_page_title: 'Поиск друзей',

    following_page_title: 'Друзья',
    following_page_no_friends: 'Нет друзей.',

    settings_page_title: 'Настройки',
    settings_form_name: 'Имя',
    settings_form_username: 'Ник',
    settings_form_username_para: 'Используется в адресе списка желаний:',
    settings_form_username_is_free: 'этот ник свободен',
    settings_form_username_is_not_free: 'такой ник занят',
    settings_form_username_mask: 'Можно использовать только латинский алфавит в нижнем регистре, цифры и&nbsp;символы _ - .',
    //settings_form_username_is_not_free: 'Someone already has that username. Try another?',
    settings_form_bd: 'День рождения',
    settings_form_hide_age: 'Скрыть возраст',
    settings_form_sex: 'Пол',
    settings_form_male: 'Мужской',
    settings_form_female: 'Женский',
    settings_form_site: 'Сайт',
    settings_form_email_para: 'Укажите вашу почту, если хотите получать уведомления о&nbsp;праздниках друзей и&nbsp;об&nbsp;изменении зарезервированных вами&nbsp;желаний.',
    settings_form_i_agree_to_delete_me: 'Я хочу удалить мой профиль и все мои данные. Я понимаю, что это необратимая операция.',
    settings_form_delete_me: 'Удалить профиль',
    settings_form_save_button_title: 'Сохранить'
};
