module.exports = {
    noscript_warning: 'Для корректной работы сайта включите, пожалуйста, JavaScript.',

    signin_via_twitter: 'Войти через Твиттер',
    signin_via_vk: 'Войти через ВКонтакте',
    signin_via_facebook: 'Войти через Фейсбук',
    signin_via_other_vk: 'или через ВКонтакте',
    signin_via_other_twitter: 'или через Твиттер',
    signin_via_other_facebook: 'или через Фейсбук',

    about: 'О проекте',
    settings: 'Настройки',
    search: 'Поиск',
    logout: 'Выйти',
    edit: 'Править',
    add: 'Добавить',
    delete: 'Удалить',
    write: 'Написать',
    hide: 'Скрыть',
    last_update: 'Последнее обновление',

    status_changed_my_mind: 'Расхотелось',
    status_make_changed_my_mind: 'Расхотеть',
    status_changed_my_mind_back: 'Захотеть обратно',
    status_presented: 'Подарили!',
    status_undo_presented: 'Убрать отметку «подарили»',
    status_bought: 'Сам{{genderPrefix}} себя порадовал{{genderPrefix}}',
    status_undo_bought: 'Убрать отметку «Сам{{genderPrefix}} себя порадовал{{genderPrefix}}»',
    status_private: 'Скрытое желание',
    private_on: 'Скрыть от чужих глаз',
    private_off: 'Опубликовать для всех',
    status_reservedByMe: 'Собираюсь подарить',
    status_remove_reserve: 'Не буду дарить',
    status_reserved: 'Зарезервировано',
    copy_wish: 'Хочу в подарок',
    post_on_vk: 'Опубликовать во ВКонтакте…',
    tweet: 'Твитнуть про желание…',
    write_post: 'Опубликовать в Фейсбуке…',
    wish_added: 'Желание добавлено в <a href="/{{username}}">ваш список</a>',
    i_want: 'Я хочу',
    on_copy_fail: 'Что-то пошло не так :( Попробуйте повторить еще раз...',

    index_page_title: 'Список ваших желаний',
    hide_wish_para: 'Это скрытое желание, которое видно только вам',

    index_page_bubble_head: 'Создайте<br>список<br>желаний',
    index_page_hearts_head: 'Сгруппируйте<br>желания<br>по&nbsp;темам',
    index_page_bird_head: 'Поделитесь<br>ссылкой<br>с&nbsp;друзьями',
    index_page_gift_head: 'Получайте<br>только<br>желанное',
    index_page_facts_about_us: 'Несколько фактов о нас',
    index_page_follow_us: 'Следите за нашими обновлениями <a href="https://vk.com/wantr">во ВКонтакте</a>, <a href="https://twitter.com/wantr_ru">Твиттере</a> и <a href="https://facebook.com/wantr.ru">Фейсбуке</a>.',

    index_page_fact_address: 'Смотрите, какой красивый адрес: <a href="http://wantr.ru/{{word}}">wantr.ru/{{word}}</a> И&nbsp;для вас найдется запоминающийся.',
    index_page_fact_antiwish: 'Антижелания — одна из наших уникальных функций — то, чего вы не&nbsp;хотели&nbsp;бы получать в&nbsp;подарок.',
    index_page_fact_currency: 'Wantr — первый сервиc, где можно указать желания в&nbsp;биткоинах и&nbsp;тенге ;)',
    index_page_fact_api: 'Хотите видеть свои желания у себя на сайте? У нас есть <a href="http://api.wantr.ru">API</a> для разработчиков.',
    index_page_fact_no_spam: 'Мы не рассылаем спам и&nbsp;рекламу.',
    index_page_fact_explore: 'Мы гордимся, что у нас есть <a href="/explore">такие целеустремленные пользователи</a>.',

    welcome_text: 'Напишите вступительный текст. Здесь может быть обращение к&nbsp;друзьям, которое не&nbsp;укладывается в&nbsp;пункты желаний.',
    wishes: 'Желания',
    wishes_empty_for_stranger: 'Список желаний пуст.',
    wishes_empty_for_owner: 'Список пуст. Добавьте несколько желаний, мечтать полезно ;)',
    antiwishes: 'Антижелания',
    antiwishes_empty: 'Список пуст. Добавьте антижелания. Это простой способ сказать «Пожалуйста, не дарите мне это».',

    birthday: 'День рождения',
    today: 'сегодня',
    hbd: 'Поздравляем с днем рождения!',
    turn: 'исполнится',
    add_bd: 'Укажите день рождения',
    age_one: 'год',
    age_two: 'года',
    age_many: 'лет',

    find_friends: 'Найдите друзей',
    add_friend: 'Добавить в друзья',
    delete_friend: 'Удалить из друзей',
    no_friends: 'Нет друзей',
    plural_friends_one: 'друг',
    plural_friends_two: 'друга',
    plural_friends_many: 'друзей',

    month_later: 'Через месяц',
    three_weeks_later: 'Через 3 недели',
    day_after_tomorrow: 'Уже послезавтра',
    tomorrow: 'Завтра',
    today_upper: 'Сегодня',
    yesterday: 'День рождения был вчера',
    just: 'только что',
    after: 'Через',
    day_one: 'день',
    day_two: 'дня',
    day_many: 'дней',
    hour_one: 'час',
    hour_two: 'часа',
    hour_many: 'часов',
    minute_one: 'минуту',
    minute_two: 'минуты',
    minute_many: 'минут',
    ago: 'назад',

    months: [
        'января',
        'февраля',
        'марта',
        'апреля',
        'мая',
        'июня',
        'июля',
        'августа',
        'сентября',
        'октября',
        'ноября',
        'декабря'
    ],

    no_search_results: 'По вашему запросу ничего не найдено.',
    type_nickname_or_username: 'Введите ник или имя пользователя',

    login_page_title: 'Стой, кто идет?',
    not_found_page_title: 'Страница не найдена',
    not_found_page_para: 'Если вы ищете пользователя «{{login}}», то его здесь нет. Возможно, он еще не завел список желаний?',
    page_500_title: 'Лежим и не жужжим',
    internal_service_error: 'Внутренняя ошибка сервиса',

    explore_page_title: '10 случайно выбранных пользователей',
    refresh: 'Обновить',
    explore_page_para: 'Не нашли знакомых лиц? Возможно, они еще не знают о нашем сервисе… пригласите их!',

    find_friends_page_title: 'Поиск друзей',
    // Контекст: найти друзей на фейсбуке
    find_friends_page_facebook: 'на фейсбуке',
    find_friends_page_vkontakte: 'во ВКонтакте',
    find_friends_page_twitter: 'в Твиттере',

    following_page_title: 'Друзья',
    following_page_no_friends: 'Нет друзей.',
    following_page_find_friends: 'Найти <a href="/{{username}}/find-friends/">моих друзей</a> из {{social}}.',
    following_page_facebook: 'Фейсбука',
    following_page_vkontakte: 'ВКонтакте',
    following_page_twitter: 'Твиттера',

    settings_page_title: 'Настройки',
    settings_form_name: 'Имя',
    settings_form_username: 'Ник',
    settings_form_username_para: 'Используется в адресе списка желаний:',
    settings_form_username_is_free: 'этот ник свободен',
    settings_form_username_is_not_free: 'такой ник занят',
    settings_form_username_mask: 'Можно использовать только латинский алфавит в нижнем регистре, цифры и&nbsp;символы _ - .',
    settings_form_bd: 'День рождения',
    settings_form_hide_age: 'Скрыть возраст',
    settings_form_sex: 'Пол',
    settings_form_male: 'Мужской',
    settings_form_female: 'Женский',
    settings_form_site: 'Сайт',
    settings_form_email_para: 'Укажите вашу почту, если хотите получать уведомления о&nbsp;праздниках друзей и&nbsp;об&nbsp;изменении зарезервированных вами&nbsp;желаний.',
    settings_form_i_agree_to_delete_me: 'Я хочу удалить мой профиль и все мои данные. Я понимаю, что это необратимая операция.',
    settings_form_delete_me: 'Удалить профиль',
    settings_form_save_button_title: 'Сохранить',
    settings_form_lang: 'Язык интерфейса',
    language_name: 'Русский',
    settings_form_facebook: 'на фейсбуке',
    settings_form_vkontakte: 'во вконтакте',
    settings_form_twitter: 'в твиттере',
    settings_form_avatar_from: 'Аватарка подгружается <a href="{{link}}" target="_blank">из вашего профиля {{social}}</a>.',

    to_profile: 'к профилю',
    welcome_text: 'Вступительный текст',
    welcome_text_placeholder: 'Можете написать вступление или пояснения, которые не выразить пунктами списка желаний',

    edit_page_antiwishes_descr: 'Перечислите, чего вы не хотите видеть в качестве подарка.',
    edit_page_save_button_title: 'Сохранить изменения',
    edit_page_wish_descr: 'Описание',
    edit_page_antiwish_descr: 'Описание',
    edit_page_link_descr: 'Ссылка',
    edit_page_price_descr: 'Цена',

    find_friends_page_empty_list: 'Вы счастливчик! Вы — первый, среди ваших друзей {{social}}, кто зарегистрировался здесь.',
    find_friends_page_empty_list_2: 'Расскажите друзьям и знакомым о Wantr!',

    category: 'Категория',
    category_name: 'Название категории:',
    create_category: 'Создать новую…',

    // titles
    html_title_api: 'Документация по API',
    html_title_media: 'Медиаматериалы и гайдлайны',
    'html_title_press-open': 'Пресс-релиз',
    html_title_friends: 'друзья',
    html_title_edit: 'Редактирование',
    html_title_settings: 'Настройки',
    html_title_404: '404',
    html_title_500: '500',
    html_title_login: 'Стой, кто идёт?',
    html_title_search: 'Поиск',
    'html_title_find-friends': 'Поиск друзей',
    html_title_user: '{{placeholder}} — желания',
    html_title_ny2014: 'С Новым годом!',
    html_title_explore: 'Наши пользователи',
    html_title_default: 'Wantr — список ваших желаний',

    smm_i_want: 'Я хочу',
    smm_wishes: 'желания',
    smm_antiwishes: 'антижелания',
    smm_antiwishes_para: 'Пожалуйста, не дарите мне',
    smm_title: 'Создайте список желаний; Сгруппируйте желания по темам; Поделитесь ссылкой с друзьями; Получайте только желанные подарки!',
    smm_slogan: '— Скажи мне чего ты хочешь, и я скажу «Заведи вишлист»',

    want: 'хочет'
};
