module.exports = {
    noscript_warning: 'Для коректної роботи сайту увімкніть, будь ласка, JavaScript.',

    signin_via_twitter: 'Увійти через Твіттер',
    signin_via_vk: 'Увійти через ВКонтакті',
    signin_via_facebook: 'Увійти через Фейсбук',
    signin_via_other_vk: 'або через ВКонтакті',
    signin_via_other_twitter: 'або через Твіттер',
    signin_via_other_facebook: 'або через Фейсбук',

    about: 'Про проект',
    settings: 'Налаштування',
    search: 'Пошук',
    logout: 'Вийти',
    edit: 'Редагувати',
    add: 'Додати',
    delete: 'Видалити',
    write: 'Написати',
    hide: 'Приховати',
    last_update: 'Свіже оновлення',

    status_changed_my_mind: 'Перехотілося',
    status_make_changed_my_mind: 'Не хочу',
    status_changed_my_mind_back: 'Знову хочу',
    status_presented: 'Подарували!',
    status_undo_presented: 'Прибрати позначку «подарували»',
    status_bought: 'Сам себе порадував',
    //status_bought: 'Сама себе порадувала',
    status_undo_bought: 'Прибрати позначку «Сам себе порадував»',
    //status_undo_bought: 'Прибрати позначку «Сама себе порадувала»',
    status_private: 'Приховане бажання',
    private_on: 'Приховати від чужих очей',
    private_off: 'Опублікувати для всіх',
    status_reservedByMe: 'Збираюся подарувати',
    status_remove_reserve: 'Не буду дарувати',
    status_reserved: 'Зарезервовано',
    copy_wish: 'Хочу в подарунок',
    post_on_vk: 'Опублікувати у ВКонтакті…',
    tweet: 'Твітнути про бажання…',
    write_post: 'Опублікувати у Фейсбук…',
    wish_added: 'Бажання додано у <a href="/{{username}}">ваш список</a>',
    i_want: 'Я хочу',
    on_copy_fail: 'Щось пішло не так :( Спробуйте повторити ще раз...',

    index_page_title: 'Список ваших бажань',
    hide_wish_para: 'Це приховане бажання, яке видно тільки вам',

    index_page_bubble_head: 'Створіть<br>список<br>бажань',
    index_page_hearts_head: 'Згрупуйте<br>бажання<br>по&nbsp;темам',
    index_page_bird_head: 'Поділіться<br>посиланням<br>з&nbsp;друзями',
    index_page_gift_head: 'Отримуйте<br>тільки<br>бажане',
    index_page_facts_about_us: 'Кілька фактів про нас',
    index_page_follow_us: 'Слідкуйте за нашими оновленнями <a href="https://vk.com/wantr">у ВКонтакті</a>, <a href="https://twitter.com/wantr_ru">Твіттері</a> та <a href="https://facebook.com/wantr.ru">Фейсбуці</a>.',

    index_page_fact_address: 'Дивіться, яка гарна адреса: <a href="http://wantr.ru/{{word}}">wantr.ru/{{word}}</a> I&nbsp;для вас знайдеться незабутня.',
    index_page_fact_antiwish: 'Антибажання — одна з наших унікальних функцій — те, чого б ви не&nbsp;хотіли&nbsp; отримати в&nbsp;подарунок.',
    index_page_fact_currency: 'Wantr — перший сервіс, де можна вказати бажання в&nbsp;біткойнах і&nbsp;теньге ;)',
    index_page_fact_api: 'Хочете бачити свої бажання у себе на сайті? В нас є <a href="http://api.wantr.ru">API</a> для розробників.',
    index_page_fact_no_spam: 'Ми не розсилаємо спам і&nbsp;рекламу.',
    index_page_fact_explore: 'Ми пишаємося, що у нас є <a href="/explore">такі цілеспрямовані користувачі</a>.',

    welcome_text: 'Напишіть вступний текст. Тут може бути звернення до&nbsp;друзів, яке не&nbsp;входить в&nbsp;пункти бажань.',
    wishes: 'Бажання',
    wishes_empty_for_stranger: 'Список бажань порожній.',
    wishes_empty_for_owner: 'Список порожній. Додайте кілька бажань, мріяти корисно ;)',
    antiwishes: 'Антибажання',
    antiwishes_empty: 'Список порожній. Додайте антибажання. Це простий спосіб сказати «Будь ласка, не даруйте мені це».',

    birthday: 'День народження',
    today: 'сьогодні',
    hbd: 'Вітаємо з Днем народження!',
    turn: 'виповниться',
    add_bd: 'Вкажіть день народження',
    age_one: 'рік',
    age_two: 'роки',
    age_many: 'років',

    find_friends: 'Знайдіть друзів',
    add_friend: 'Додати в друзі',
    delete_friend: 'Видалити з друзів',
    no_friends: 'Немає друзів',
    plural_friends_one: 'друг',
    plural_friends_two: 'друга',
    plural_friends_many: 'друзів',

    month_later: 'Через місяць',
    three_weeks_later: 'Через 3 тижні',
    day_after_tomorrow: 'Вже післязавтра',
    tomorrow: 'Завтра',
    today_upper: 'Сьогодні',
    yesterday: 'Вчора',
    just: 'щойно',
    after: 'Через',
    day_one: 'день',
    day_two: 'дні',
    day_many: 'днів',
    hour_one: 'годину',
    hour_two: 'години',
    hour_many: 'годин',
    minute_one: 'хвилину',
    minute_two: 'хвилини',
    minute_many: 'хвилин',
    ago: 'тому',

    months: [
        'січня',
        'лютого',
        'березня',
        'квітня',
        'травня',
        'червня',
        'липня',
        'серпня',
        'вересня',
        'жовтня',
        'листопада',
        'грудня'
    ],

    no_search_results: 'За вашим запитом нічого не знайдено.',
    type_nickname_or_username: 'Введіть нік або ім\'я користувача',

    login_page_title: 'Стій, хто йде?',
    not_found_page_title: 'Сторінку не знайдено',
    not_found_page_para: 'Якщо ви шукаєте користувача «{{login}}», то його тут немає. Можливо, він ще не завів список бажань?',
    page_500_title: 'Лежимо й не дзижчимо',
    internal_service_error: 'Внутрішня помилка сервісу',

    explore_page_title: '10 випадково обраних користувачів',
    refresh: 'Оновити',
    explore_page_para: 'Не знайшли знайомих облич? Можливо, вони ще не знають про наш сервіс… запросіть їх!',

    find_friends_page_title: 'Пошук друзів',
    // Контекст: знайти друзів на фейсбуці
    find_friends_page_facebook: 'на фейсбуці',
    find_friends_page_vkontakte: 'у ВКонтакті',
    find_friends_page_twitter: 'в Твіттері',

    following_page_title: 'Друзі',
    following_page_no_friends: 'Немає друзів.',
    following_page_find_friends: 'Знайти <a href="/{{username}}/find-friends/">моїх друзів</a> з {{social}}.',
    following_page_facebook: 'Фейсбука',
    following_page_vkontakte: 'ВКонтакта',
    following_page_twitter: 'Твіттера',

    settings_page_title: 'Налаштування',
    settings_form_name: 'Iм\'я',
    settings_form_username: 'Нік',
    settings_form_username_para: 'Використовується в адресі списку бажань:',
    settings_form_username_is_free: 'цей нік вільний',
    settings_form_username_is_not_free: 'такий нік зайнятий',
    settings_form_username_mask: 'Можна використовувати лише латинський алфавіт в нижньому регістрі, цифри і&nbsp;символи _ - .',
    settings_form_bd: 'День народження',
    settings_form_hide_age: 'Приховати вік',
    settings_form_sex: 'Стать',
    settings_form_male: 'Чоловіча',
    settings_form_female: 'Жіноча',
    settings_form_site: 'Сайт',
    settings_form_email_para: 'Вкажіть вашу пошту, якщо бажаєте отримувати повідомлення про&nbsp; свята друзів і&nbsp;про&nbsp;зміни зарезервованих вами&nbsp;бажань.',
    settings_form_i_agree_to_delete_me: 'Я хочу видалити мій профіль і всі мої дані. Я розумію, що це незворотня операція.',
    settings_form_delete_me: 'Видалити профіль',
    settings_form_save_button_title: 'Зберегти',
    settings_form_lang: 'Мова інтерфейсу',
    language_name: 'Українська',
    settings_form_facebook: 'на фейсбуці',
    settings_form_vkontakte: 'у вконтакті',
    settings_form_twitter: 'в твіттері',
    settings_form_avatar_from: 'Аватарка підвантажується <a href="{{link}}" target="_blank">з вашого профілю {{social}}</a>.',

    to_profile: 'до профіля',
    welcome_text: 'Вступний текст',
    welcome_text_placeholder: 'Можете написати вступ або пояснення, яке не висловити пунктами списку бажань',

    edit_page_antiwishes_descr: 'Опишіть, чого б ви не хотіли в подарунок.',
    edit_page_save_button_title: 'Зберегти зміни',
    edit_page_wish_descr: 'Опис',
    edit_page_antiwish_descr: 'Опис',
    edit_page_link_descr: 'Посилання',
    edit_page_price_descr: 'Ціна',

    find_friends_page_empty_list: 'Ви щасливчик! Ви — перший, серед ваших друзів {{social}}, хто зареєструвався тут.',
    find_friends_page_empty_list_2: 'Розкажіть друзям і знайомим про Wantr!',

    category: 'Категорія',
    category_name: 'Назва категорії:',
    create_category: 'Створити нову…',

    // titles
    html_title_api: 'Документація по API',
    html_title_media: 'Медіаматеріали і гайдлайни',
    'html_title_press-open': 'Прес-реліз',
    html_title_friends: 'друзі',
    html_title_edit: 'Редагування',
    html_title_settings: 'Налаштування',
    html_title_404: '404',
    html_title_500: '500',
    html_title_login: 'Стій, хто йде?',
    html_title_search: 'Пошук',
    'html_title_find-friends': 'Пошук друзів',
    html_title_user: '{{placeholder}} — бажання',
    html_title_ny2014: 'З Новим роком!',
    html_title_explore: 'Наші користувачі',
    html_title_default: 'Wantr — список ваших бажань',

    smm_i_want: 'Я хочу',
    smm_wishes: 'бажання',
    smm_antiwishes: 'антибажання',
    smm_antiwishes_para: 'Будь ласка, не даруйте мені',
    smm_title: 'Створіть список бажань; Згрупуйте бажання за темами; Поділіться посиланням з друзями; Отримуйте тільки бажані подарунки!',
    smm_slogan: '— Скажи мені чого ти хочеш, і я скажу «Заведи вішліст»',

    want: 'хоче'
};
